apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: angular-frontend
  name: angular-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: angular-frontend
    spec:
      containers:
      - image: nginx:alpine
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
